baseurl = "https://gsergey418.github.io/"
theme = "hugo-coder"

defaultContentLanguage = "en"

[markup.highlight]
style = "github-dark"

[params]
  keywords = "developer,personal"
  avatarurl = "images/avatar.jpg"

  since = 2024

  enableTwemoji = true

[languages]
  [languages.en]
    disabled = false
    contentDir = "content/en"
    languageCode = 'en-US'
    languageName = 'English'
    weight = 0

    title = 'Sergey Gorbunov'

    [languages.en.params]
      author = "Sergey Gorbunov"
      info = "I'm a backend developer from Moscow."
      description = "Sergey's personal website"
    

  [languages.ru]
    disabled = false
    contentDir = "content/ru"
    languageCode = 'ru-RU'
    languageName = 'Русский'
    weight = 1

    title = 'Сергей Горбунов'

    [languages.ru.params]
      author = "Сергей Горбунов"
      info = "Я бэкенд-разработчик из Москвы."
      description = "Личный сайт Сергея"


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Telegram"
  icon = "fa-brands fa-telegram fa-2x"
  weight = 3
  url = "https://t.me/gsergey418"
[[params.social]]
  name = "E-Mail"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 3
  url = "mailto:gsergey418@yandex.ru"